name: real_time_translator
description: A Flutter app to translate text in real time
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  camera: ^0.5.8+11
  firebase_ml_vision: ^0.9.9

  flutter:
    sdk: flutter

dev_dependencies:
  dapackages: ^1.4.0

flutter:
  uses-material-design: true